version: "3"

services:
  nginxcustom:
    build: nginx/.
    network_mode: host
  svc1:
    build: service/.
    ports:
      - "8080:8080"

  # Uncomment the following block to start a second instance of the service
  # svc2:
  #       build: service/.
  #       ports:
  #         - "8081:8080" # Notice the port is 8081
  